<?php

/**
 * @file
 * Drupal module to access the Kraftwagen Environment.
 */

/**
 * Default environment value if no environment can be found. 
 */
define('KW_ENVIRONMENT_DEFAULT', 'production');

/**
 * Get the value for the environment.
 *
 * @return
 *   The environment value
 */
function kw_environment() {
  $environment = &drupal_static(__FUNCTION__, NULL);

  if (!isset($environment)) {
    if ($cache = cache_get(__FUNCTION__)) {
      $environment = $cache->data;
    }

    if (!isset($environment)) {
      $location = kw_environment_location();
      if (!$location) {
        $environment = KW_ENVIRONMENT_DEFAULT;
      }

      $environment = file_get_contents($location);
      cache_set(__FUNCTION__, $environment);
    }
  }

  return $environment ? $environment : KW_ENVIRONMENT_DEFAULT;
}

/**
 * Get the location of environment file
 *
 * @return
 *   Path to the environment file, or FALSE if no path is set or detected.
 */
function kw_environment_location() {
  $location = &drupal_static(__FUNCTION__);

  if (!isset($location)) {
    $location = variable_get(__FUNCTION__, NULL);
  }

  if (!isset($location)) {
    $location = _kw_enviroment_location();
    variable_set(__FUNCTION__, $location);
    variable_set(__FUNCTION__ . '_source', 'auto');
  }

  return $location;
}

/**
 * Internal helper function. Detect the location of the environment.
 */
function _kw_enviroment_location() {
  $dir = realpath(DRUPAL_ROOT);
  if (is_file($dir)) {
    $dir = dirname($dir);
  }

  if (!is_dir($dir)) {
    return FALSE;
  }

  // traverse upwards
  while ($dir) {
    $env_path = $dir . DIRECTORY_SEPARATOR . 'cnf' . DIRECTORY_SEPARATOR . 'environment';
    if (file_exists($env_path)) {
      return $env_path
    }

    // try to find the parent directory
    $prev_dir = $dir;
    $dir = dirname($dir);

    // dirname('/') == '/'
    if ($dir == $prev_dir) {
      return FALSE;
    }
  }

  return FALSE;
}
